#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '20201942'
      #password 密码
      password: '031112'
      #address 地址，定位信息
      address: 中国黑龙江省哈尔滨市南岗区学府东四道街
      #email 接受通知消息的邮箱
      email: 2684117397@qq.com
      #school 学校全称
      school: 黑龙江大学
      #lon 经度
      lon: '126.634765'
      #lat 纬度
      lat: '45.712103'
      #abnormalReason 反馈信息
      abnormalReason:
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  #是否检查问题,true检查，false不检查
  check: true
  #附加信息组默认选项配置，没有可留空
  defaults:
  #附加信息组默认选项配置，按顺序，可留空
      - default:
          #表单项标题
          title: 晚自测体温是否正常
          #表单项默认值
          value: 正常
  #多个额外选项配置
#    - default:
#        #表单项标题
#        title: 体温
#        #表单项默认值
#        value: 正常