user:
  #username 学号或者工号
  username: '120000000000'
  #tellphone 电话号码
  tellphone: '13000000000'
  #address 地址，定位信息
  address: 中国广东省深圳市xx区xx街道xx路
  #email 接受通知消息的邮箱（已弃用，可以不填）
  email: 895996939@qq.com
  #lon 当前位置经度，可以访问http://api.map.baidu.com/lbsapi/getpoint/获取
  lon: '116.401969'
  #lat 当前位置纬度
  lat: '39.915599'
  #school 学校全称
  school: 辽宁科技大学
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理，不会配置就执行generate.py
    - default:
        title: 今日体温是（℃）
        type: '1'
        value: '36.1'
    - default:
        title: 今日是否有发热、咳嗽等症状？
        type: '2'
        value: 否
    - default:
        title: 是否有中高风险地区旅居史？
        type: '2'
        value: 否
    - default:
        title: 是否被要求隔离
        type: '2'
        value: 否
    - default:
        title: 是否为确诊、疑似病例或无症状感染者？
        type: '2'
        value: 否
        
Info:
  ServerChan: SCTXXXXXXXXXXXXXXXXXXXX # 填写Server酱的SCKEY 微信推送结果 详情请看https://sct.ftqq.com/ 
